import aircnc from 'assets/images/aircnc.png';
import bethehero from 'assets/images/be-the-hero.png';
import covid19 from 'assets/images/covid19.png';
import devradar from 'assets/images/devradar.png';
import dowhile from 'assets/images/dowhile.png';
import ecoleta from 'assets/images/ecoleta.png';
import finances from 'assets/images/finances.png';
import happy from 'assets/images/happy.png';
import hello from 'assets/images/hello.png';
import hospitalscore from 'assets/images/hospitalscore.png';
import letmeask from 'assets/images/letmeask.png';
import marvel from 'assets/images/marvel.png';
import menuria from 'assets/images/menuria.png';
import moveit from 'assets/images/moveit.png';
import neon from 'assets/images/neon.png';
import picpay from 'assets/images/picpay.png';
import plantmanager from 'assets/images/plantmanager.png';
import product from 'assets/images/product.png';
import proffy from 'assets/images/proffy.png';
import twitch from 'assets/images/twitch.png';

export const portfolio = [
  {
    name: 'DoWhile · NLW#7',
    image: dowhile,
    uri: 'dowhile',
    deploy: 'https://dowhile-oficial.vercel.app',
    category: ['all', 'frontend'],
    item1: 'react',
    item2: 'vite',
    item3: 'ts',
  },
  {
    name: 'Letmeask · NLW#6',
    image: letmeask,
    uri: 'letmeask',
    deploy: 'https://letmeask-oficial.web.app/',
    category: ['all', 'frontend'],
    item1: 'react',
    item2: 'firebase',
    item3: 'ts',
  },
  {
    name: 'Plant Manager · NLW#5',
    image: plantmanager,
    uri: 'plantmanager',
    deploy: 'https://expo.io/@ialexanderbrito/plantmanager',
    category: ['all', 'mobile'],
    item1: 'expo',
    item2: 'react-native',
    item3: 'ts',
  },
  {
    name: 'Banco Neon · Clone',
    image: neon,
    uri: 'neon-clone',
    deploy: 'https://neon-clone.vercel.app/',
    category: ['all', 'frontend'],
    item1: 'react',
    item2: 'nextjs',
    item3: 'js',
  },

  {
    name: 'Hello · TCC',
    image: hello,
    uri: 'hello',
    category: ['all', 'frontend'],
    item1: 'react',
    item2: 'node.js',
    item3: 'js',
    item4: 'firebase',
    item5: 'arduino',
  },
  {
    name: 'Menuria',
    image: menuria,
    uri: 'menuria',
    deploy: 'https://menuria-oficial.netlify.app/',
    category: ['all', 'mobile'],
    item1: 'expo',
    item2: 'react',
    item3: 'js',
    item4: 'node.js',
  },
  {
    name: 'Finanças App',
    image: finances,
    uri: 'finances',
    deploy: 'https://expo.io/@ialexanderbrito/finances',
    category: ['all', 'mobile'],
    item1: 'expo',
    item2: 'react-native',
    item3: 'ts',
  },
  {
    name: 'Twitch · Clone',
    image: twitch,
    uri: 'twitch-clone',
    deploy: 'https://expo.io/@ialexanderbrito/twitchtv',
    category: ['all', 'mobile'],
    item1: 'expo',
    item2: 'react-native',
    item3: 'ts',
  },
  {
    name: 'Marvel App',
    image: marvel,
    uri: 'marvel-app',
    deploy: 'https://expo.io/@ialexanderbrito/marvel-app',
    category: ['all', 'mobile'],
    item1: 'expo',
    item2: 'react-native',
    item3: 'ts',
    item4: 'node.js',
  },
  {
    name: 'Happy · NLW#4',
    image: moveit,
    uri: 'moveit',
    deploy: 'https://moveit-oficial.netlify.app/',
    category: ['all', 'frontend'],
    item1: 'react',
    item2: 'ts',
  },
  {
    name: 'Happy · NLW#3',
    image: happy,
    uri: 'happy',
    deploy: 'https://happy-oficial.netlify.app/',
    category: ['all', 'frontend'],
    item1: 'expo',
    item2: 'react',
    item3: 'ts',
    item4: 'node.js',
  },
  {
    name: 'Proffy · NLW#2',
    image: proffy,
    uri: 'proffy',
    deploy: 'https://proffy-oficial.netlify.app/',
    category: ['all', 'frontend'],
    item1: 'expo',
    item2: 'react',
    item3: 'ts',
    item4: 'node.js',
  },
  {
    name: 'Ecoleta · NLW#1',
    image: ecoleta,
    uri: 'ecoleta',
    deploy: 'https://ecoleta-oficial.netlify.app/',
    category: ['all', 'frontend'],
    item1: 'expo',
    item2: 'react',
    item3: 'ts',
    item4: 'node.js',
  },
  {
    name: 'Hospital Score',
    image: hospitalscore,
    uri: 'hospital-score',
    category: ['all', 'mobile', 'ux-ui'],
    item1: 'expo',
    item2: 'react-native',
    item3: 'js',
    item4: 'node.js',
  },
  {
    name: 'Covid-19 App',
    image: covid19,
    uri: 'covid19-app',
    deploy: 'https://expo.io/@ialexanderbrito/covid19',
    category: ['all', 'mobile'],
    item1: 'expo',
    item2: 'react-native',
    item3: 'js',
  },
  {
    name: 'PicPay · Clone',
    image: picpay,
    uri: 'picpay-clone',
    category: ['all', 'mobile'],
    item1: 'expo',
    item2: 'react-native',
    item3: 'js',
  },
  {
    name: 'Carrinho de Loja',
    image: product,
    uri: 'product',
    category: ['all', 'frontend'],
    item1: 'html',
    item2: 'css',
  },
  {
    name: 'Be The Hero · OmniStack#11',
    image: bethehero,
    uri: 'be-the-hero',
    deploy: 'https://be-the-hero-oficial.netlify.app/',
    category: ['all', 'frontend'],
    item1: 'expo',
    item2: 'react',
    item3: 'js',
    item4: 'node.js',
  },
  {
    name: 'DevRadar · OmniStack#10',
    image: devradar,
    uri: 'dev-radar',
    deploy: 'https://dev-radar-oficial.netlify.app/',
    category: ['all', 'frontend'],
    item1: 'expo',
    item2: 'react',
    item3: 'js',
    item4: 'node.js',
  },
  {
    name: 'Aircnc · OmniStack#9',
    image: aircnc,
    uri: 'aircnc',
    deploy: 'mohttps://aircnc-oficial.netlify.app/veit',
    category: ['all', 'frontend'],
    item1: 'expo',
    item2: 'react',
    item3: 'js',
    item4: 'node.js',
  },
];
